config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
	  root 'devise/sessions#new'
	end
  resources :home do
    collection do
      get :menu
      get :users
      put 'update/:id/', to: 'home#update'
      get :invoice
    end
   
  end 
  resources :residents 
  resources :residents_agreements 
  resources :support_plans 
  resources :complaints 
  resources :bookings 
  resources :incident_reports 
  resources :srs_referals 
  resources :profile 
  resources :transfer_details 
  resources :file_reports
  resources :staff_rosters

end

app/models/residents_agreement.rb
class ResidentsAgreement < ApplicationRecord
end

app/controllers/residents_agreements_controller.rb
# derived from base controller
class ResidentsAgreementsController < BaseController

  #authenticate if user logged.
  before_action :authenticate_user!

	def index
   	@page_title = "Residents Service Agreements | Home"
   	get_collection
	end
	

  def new
	  new_resident_agreement
	 	@page_title = "Residents  Service Agreements | New RSA"   
	end
	
	def show
		@resident_agreement=ResidentsAgreement.find(params[:id])
	end
	
	def edit
		@resident_agreement=ResidentsAgreement.find(params[:id])
   	@page_title = "Residents  Service Agreements | Update RSA"   	
	end
  
  def create
	 	@resident_agreement=ResidentsAgreement.new(permitted_params)
    if @resident_agreement.valid?
      @resident_agreement.save
      redirect_to residents_agreements_path
	 	else
      redirect_to home_index_path

	 	end
	end

	def update
    @resident_agreement=ResidentsAgreement.find(params[:id])
	  @resident_agreement.update(permitted_params)
	  if @resident_agreement.save
      redirect_to residents_agreements_path
		else
      redirect_to home_index_path

		end
	end
	
  def destroy
		@resident_agreement = ResidentsAgreement.find(params[:id])
    if @resident_agreement.destroy
      redirect_to residents_agreements_path
    else
      redirect_to home_index_path
    end
  end
    
  # --------------
  # Fetch Methods
  # --------------

	private

	def permitted_params
    params.require(:residents_agreement).permit(:user_name,:room_no,:bed,:dob,:guardian,:admin,:person_nominated,:stay_period,:fixed_period,:ending_on,:accommodation_fee,:payment_via,:payment_frequency,:advanced_fee,:security_deposit,:reservation_charge,:establishment,:condition_report_status,:services,:personal_properties,:special_items)
	end

  def new_resident_agreement
    @resident_agreement = ResidentsAgreement.new
  end

  def existing_resident_agreement
    @resident_agreement = ResidentsAgreement.find_by_id(params[:id])
  end

  def get_collection
    @relation = ResidentsAgreement.where("")

    apply_filters

    @order_by = "created_at DESC" unless @order_by
    @resident_agreements = @r_objects = @relation.order(@order_by).all #page(@current_page).per(@per_page)
  end
  
  def apply_filters
    @query = params[:q]
    @relation = @relation.search(@query) if @query && !@query.blank?
    #@relation = @relation.search_only_name(params[:filters].try(:[], :name))
    
  end




	
end

app/views/residents_agreements/edit.html.erb
<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title"><b>Update Resident Service Agreement</b></h3>
    </div>
    <div class="row">
      <div class="col-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <%= render partial: 'residents_agreements/form/form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/residents_agreements/index.html.erb
<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title"><b>Resident Service Agreements</b></h3>
        <div class="col-md-4">
          <%= link_to '+ Add New RSA', new_residents_agreement_path, :class =>"btn btn-success", :remote => true %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table">
                  <thead style="background-color: #1294a3; color: white;">
                    <tr>
                      <th>ID</th>
                      <th>User</th>
                      <th>Created_at</th>
                      <th style="align-content: center;">Action</th>
                      <th></th>
                        <th></th>
                    </tr>
                  </thead>
      
                  <tbody >
                    <% @resident_agreements.each_with_index do |resident_agreement, i| %>
                      <tr id='residents_ROW_<%= resident_agreement.id %>'>
                        <td>
                          <span><%= i+1 %></span>
                        </td>
                        <td>
                          <span><%= resident_agreement.user_name %></span>
                        </td>
                        
                        <td>
                          <span><%= resident_agreement.created_at.in_time_zone("Asia/Muscat").strftime('%d %B %Y, %H:%M') if resident_agreement.created_at %></span>
                        </td>
                        <td>
                          <%= button_to residents_agreement_path(resident_agreement),:method => :get, :class => "btn-success" do %><i class="fa fa-eye"></i><% end %>
                        </td>
                        <td><%= button_to edit_residents_agreement_path(resident_agreement), :method => :get, :remote => true, :class => "btn-success" do %><i class="fa fa-edit"></i><% end %>
                        </td>
                        <td><%= button_to residents_agreement_path(resident_agreement), :method => :delete, :remote => true, data: {confirm: "Are you sure you want to delete this?"}, :class => "btn-danger" do %><i class="fa fa-trash"></i><% end %>     </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>



        
      

app/views/residents_agreements/new.html.erb
<div class="main-panel">
  <div class="content-wrapper">
    <div class="page-header">
      <h3 class="page-title"><b>Add New Resident Service Agreement</b></h3>     
    </div>
    <div class="row">
      <div class="col-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body">
            <%= render partial: 'residents_agreements/form/form' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/residents_agreements/show.html.erb
<div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>Resident Service Agreements </b></h3>
               <div class="col-md-4">
           <%= link_to '+ Add New RSA', new_residents_agreement_path, :class =>"btn btn-success", :remote => true %>
  
              </div>
             
            </div>
        <div class="row">
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                      <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                                  <label for="exampleInputName1">Resident Name</label>
                                </div>
                              </div>
                              <div class="col-9">
                                <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.user_name %></label>
                              </div>
                          </div>
                      <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputroom">Room No</label>
                      </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.room_no %></label>
                    </div>
                      </div>
                      <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputbed">Bed</label>
                      </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.bed %></label>
                    </div>
                  </div>
                  <div class="row">
                          <div class="col-3">
                    <div class="form-group">
                        <label for="exampleInputdate">Date of Birth</label>
                      </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.dob %></label>
                    </div>      
                    </div>
                   <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputguardian">Guardian</label>
                      </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.guardian %></label>
                    </div>
                  </div>
                          <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputadmin">Administrator</label>
                        </div>
                    </div>
                        <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.admin %></label>
                    </div>
                  </div>
                      <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputperson">Person Nominated</label>
                        </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.person_nominated %></label>
                    </div>        
                    </div>      
                  <p class="card-description">DURATION OF STAY</p>
                    <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputstayform">Indefinite period of stay form</label>
                        </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.stay_period %></label>
                    </div>  
                       </div>
                   <div class="row">
                      <div class="col-3">
                          <div class="form-group">
                    <label for="exampleInputfixed">Fixed period stay form</label>
                    </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.fixed_period %></label>
                    </div>
                    </div>
                   <div class="row">
                      <div class="col-3">
                        <div class="form-group">
                          <label for="exampleInputending">Ending on</label>
                        </div>
                        </div>
                        <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.ending_on %></label>
                    </div>    
                    </div>
                    <p class="card-description">FEE AND CHARGES</p>
                   <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                      <label for="exampleInputsupport">Fee for accommodation and personal support</label>
                      </div>
                    </div>
                        <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.accommodation_fee %></label>
                    </div>      
                   </div>
                   <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputpay">How to pay</label>
                        </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.payment_via %></label>
                    </div>
                  </div>
                        <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputpayment">Frequency of payment</label>
                        </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.payment_frequency %></label>
                    </div>
                  </div>
                    <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputitems">Fee in advance charged for other items/service provide by SRS</label>
                        </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.advanced_fee %></label>
                    </div>
                      </div>
                    <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputdeposite">Security deposite charged</label>
                        </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.security_deposit %></label>
                    </div>
                  </div>
                    <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputreservation">Reservation for charged</label>
                        </div>
                    </div>
                        <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.reservation_charge %></label>
                    </div>  
                  </div>
                    <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputestablishment">Establishment for charged</label>
                        </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.establishment %></label>
                    </div> </div>
                    <p class="card-description">INDIVIDUAL SPECIFIES</p>
                   <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputcondition">Condition report provided to the resident?</label>
                      </div>
                    </div>
                   <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.condition_report_status %></label>
                    </div> 
                  </div>
                   <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputresident">Specify items and services provided to the resident </label>
                        </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.services %></label>
                    </div>                      
                  </div>
                  <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputapply">Any special items that may apply to the resident </label>
                        </div>
                    </div>
                        <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.special_items %></label>
                    </div>
                      </div>
                   <div class="row">
                          <div class="col-3">
                              <div class="form-group">
                        <label for="exampleInputproperties">Personal properties belonging resident brought into SRS</label>
                        </div>
                    </div>
                       <div class="col-9">
                      <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @resident_agreement.personal_properties %></label>
                    </div>
                      </div>
                      
                      
                     </div>
                   </div>
                 </div>
               </div>
             </div>
           </div>
         </div>
       </div>