config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
	  root 'devise/sessions#new'
	end
  resources :home do
    collection do
      get :menu
      get :users
      put 'update/:id/', to: 'home#update'
      get :invoice
    end
   
  end 
  resources :residents 
  resources :residents_agreements 
  resources :support_plans 
  resources :complaints 
  resources :bookings 
  resources :incident_reports 
  resources :srs_referals 
  resources :profile 
  resources :transfer_details 
  resources :file_reports
  resources :staff_rosters

end

app/models/incident_report.rb
class IncidentReport < ApplicationRecord
 
    
end

app/controllers/incident_reports_controller.rb
# derived from base controller
class IncidentReportsController < BaseController

  #authenticate if user logged.
  before_action :authenticate_user!

	def index
   	@page_title = "Incident Reports | Home"
   	get_collection
	end
	
  def new
    new_incident
   	@page_title = "Incident Reports | New Incident Reports"   
	end
	
	def show
  @page_title = "Incident Reports"
	@incident_report=IncidentReport.find(params[:id])
	end
	
	def edit
		@incident_report=IncidentReport.find(params[:id])
   	@page_title = "Incident Reports | Update Incident Reports"   	
	end
  
  def create
	  @incident_report=IncidentReport.new(permitted_params)
    if @incident_report.valid?
      @incident_report.save
      redirect_to incident_reports_path
	 	else
      redirect_to home_index_path

	 	end
	end

	def update
    @incident_report=IncidentReport.find(params[:id])
	  @incident_report.update(permitted_params)
	  if @incident_report.save
      redirect_to incident_reports_path
		else
      redirect_to home_index_path

		end
	end
	
  def destroy
		@incident_report = IncidentReport.find(params[:id])
    if @incident_report.destroy
      redirect_to incident_reports_path
    else
      redirect_to home_index_path
    end
  end
    
  # --------------
  # Fetch Methods
  # --------------

	private

	def permitted_params
    params.require(:incident_report).permit(:user_name, :incident_type, :other_type, :description, :action, :staff, :follow_notes, :follow_staff, :person_other, :notify_date)
	end

  def new_incident
    @incident_report = IncidentReport.new
  end

  def existing_incident
    @incident_report = IncidentReport.find_by_id(params[:id])
  end

  def get_collection
    @relation = IncidentReport.where("")

    apply_filters

    @order_by = "created_at DESC" unless @order_by
    @incident_reports = @r_objects = @relation.order(@order_by).all #page(@current_page).per(@per_page)
  end
  
  def apply_filters
    @query = params[:q]
    @relation = @relation.search(@query) if @query && !@query.blank?
    #@relation = @relation.search_only_name(params[:filters].try(:[], :name))
    
  end



	



	
end

app/views/incident_reports/edit.html.erb
<div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>Update Incident Report</b></h3>
             
            </div>
            <div class="row">
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
  					<%= render partial: 'incident_reports/form/form' %>

                  	</div>
                </div>
              </div>
            </div>
          </div>
        </div>

app/views/incident_reports/index.html.erb
<div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>Incident Reports</b></h3>
               <div class="col-md-4">
            <%= link_to '+ Add New Report', new_incident_report_path, :class =>"btn btn-success", :remote => true %>
  
              </div>
             
            </div>
           <div class="row">
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                   
                    <div class="table-responsive">
                      <table class="table">
                        <thead style="background-color: #1294a3; color: white;">
                          <tr>
                            <th>ID</th>
                            <th>User Name</th>
                            <th>Type of Incident</th>
                            <th>Created_at</th>
                            <th style="align-content: center;">Action</th>
                            <th></th>
                              <th></th>
                          </tr>
                        </thead>
                        
    <tbody >
      <% @incident_reports.each_with_index do |incident, i| %>
        <tr id='incidents_ROW_<%= incident.id %>'>
          <td>
            <span><%= i+1 %></span>
          </td>
          <td>
            <span><%= incident.user_name %></span>
          </td>
          <td>
            <span><%= incident.incident_type %></span>
          </td>
          <td>
            <span><%= incident.created_at.in_time_zone("Asia/Muscat").strftime('%d %B %Y, %H:%M') if incident.created_at %></span>
          </td>
          <td>
            <%= button_to incident_report_path(incident),:method => :get, :class => "btn-success" do %><i class="fa fa-eye"></i><% end %></td>
            <td><%= button_to edit_incident_report_path(incident), :method => :get, :remote => true, :class => "btn-success" do %><i class="fa fa-edit"></i><% end %></td>
            <td><%= button_to incident_report_path(incident), :method => :delete, :remote => true, data: {confirm: "Are you sure you want to delete this?"}, :class => "btn-danger" do %><i class="fa fa-trash"></i><% end %>
           
          </td>
        </tr>
      <% end %>
    </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>

app/views/incident_reports/new.html.erb
<div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>Add new Incident Report</b></h3>
             
            </div>
            <div class="row">
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
  					         <%= render partial: 'incident_reports/form/form' %>

                  	</div>
                </div>
              </div>
            </div>
          </div>
        </div>

app/views/incident_reports/show.html.erb
<div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>Incident Report</b></h3>
               <div class="col-md-4">
           
              </div>
             
            </div>
           <div class="row">
              <div class="col-12 grid-margin stretch-card">
              	<div class="card">
                  <div class="card-body">
     				 <form class="forms-sample">
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleInputPersonal">Name</label>
                      </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.user_name %></label>

                      </div>
                     </div>
						<div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleInputPersonal">Type of Incident</label>
                        </div>
                     </div>
                      <div class="col-9">
                        
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.incident_type %></label>
                      </div>
                      </div>  
                         
                      
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleInputEating">Other Type</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.other_type %></label>
                      </div>
                      </div>	
                      <div class="row">
                      <div class="col-3">
                       <div class="form-group">
                        <label for="exampleInputMobility">Description of incident</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.description %></label>
  					</div>
  					</div>
  					<div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleInputHealth">Action Taken</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.action %></label>
                      </div>
                      </div>
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleSelectMedication">Staff Member</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.staff %></label>
                      </div>
                      </div>
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleSelectSocial">Follow Up/Notes</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.follow_notes %></label>
                        </div>
                      </div>
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleSelectBehaviour">Follow Up staff</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.follow_staff %></label>
   					 </div>
   					 </div>
   					 <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleSelectGoal">Persons Notified</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.person_other %></label>
          				 </div>
                          </div>
                          <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleSelectGoal">Time/Date of notification</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @incident_report.notify_date %></label>
                   </div>
                          </div>
                      
                      
                     </form>
                  </div>
              </div>

              </div>
          </div>
      </div>
  </div>