config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
	  root 'devise/sessions#new'
	end
  resources :home do
    collection do
      get :menu
      get :users
      put 'update/:id/', to: 'home#update'
      get :invoice
    end
   
  end 
  resources :residents 
  resources :residents_agreements 
  resources :support_plans 
  resources :complaints 
  resources :bookings 
  resources :incident_reports 
  resources :srs_referals 
  resources :profile 
  resources :transfer_details 
  resources :file_reports
  resources :staff_rosters

end

app/controllers/home_controller.rb
# derived from base controller
class HomeController < BaseController

  #authenticate if user logged.
  before_action :authenticate_user!,except:[:new]

	def index
		@user_count = User.count
		@bookings = Booking.count
		@icreports = IncidentReport.count
		@complaints = Complaint.count
		@files = FileReport.count
		@rsa = ResidentsAgreement.count

	end
	def menu	
	end
   

	def invoice
		
	end

	def users
		get_collection
	end
	def show	
	  @user = User.find(params[:id])
	end

	def update
	  @user=User.find('1')
	  @user.update(permitted_params)
	  if @user.save
      redirect_to home_path(current_user)
		else
      redirect_to home_index_path
		end
		
	end

	

	private
		def get_collection
	    @relation = User.where("")

	    @order_by = "created_at DESC" unless @order_by
	    @users = @r_objects = @relation.order(@order_by).all #page(@current_page).per(@per_page)
	  end

	  def permitted_params
        params.require(:users).permit(:name, :email)
	end
	
end

app/views/home/index.html.erb
<div class="main-panel">
          <div class="content-wrapper pb-0">
            <div class="page-header flex-wrap">
              <h3 class="mb-0"> Hi, welcome back! <span class="pl-0 h6 pl-sm-2 text-muted d-inline-block">SRS MANAGER APPLICATION</span>
              </h3>
              <!--<div class="d-flex">
                <button type="button" class="btn btn-sm bg-white btn-icon-text border">
                  <i class="mdi mdi-email btn-icon-prepend"></i> Email </button>
                <button type="button" class="btn btn-sm bg-white btn-icon-text border ml-3">
                  <i class="mdi mdi-printer btn-icon-prepend"></i> Print </button>
                <button type="button" class="btn btn-sm ml-3 btn-success"> Add User </button>
              </div>-->
            </div>
            <div class="row">              
                <div class="card" style="width: 1000px; height: 600px; padding-bottom: 10px;">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-sm-7">
                        <h5>SRS MANAGER</h5>
                        <!--<p class="text-muted"> Show overview jan 2019 - Dec 2020 <a class="text-muted font-weight-medium pl-2" href="#"><u>See Details</u></a>
                        </p>
                      </div>
                      <div class="col-sm-5 text-md-right">
                        <button type="button" class="btn btn-icon-text mb-3 mb-sm-0 btn-inverse-primary font-weight-normal">
                          <i class="mdi mdi-email btn-icon-prepend"></i>Download Report </button>-->
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-4">
                        <div class="card bg-warning mb-3 mb-sm-0">
                      <div class="card-body px-3 py-4">
                        <div class="d-flex justify-content-between align-items-start">
                          <div class="color-card">
                            <p class="mb-0 color-card-head">Customers</p>
                            <h2 class="text-white"> <%= @user_count %>
                            </h2>
                          </div>
                          
                        </div>
                       </div>
                    </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="card bg-danger mb-3 mb-sm-0">
                      <div class="card-body px-3 py-4">
                        <div class="d-flex justify-content-between align-items-start">
                          <div class="color-card">
                            <p class="mb-0 color-card-head">Bookings</p>
                            <h2 class="text-white"><%= @bookings %>
                            </h2>
                          </div>
                         
                        </div>
                      </div>
                          </div>  
                                              </div>
                      <div class="col-sm-4">
                          <div class="card  bg-primary  mb-3 mb-sm-0">
                      <div class="card-body px-3 py-4">
                        <div class="d-flex justify-content-between align-items-start">
                          <div class="color-card">
                            <p class="mb-0 color-card-head">Incident Reports</p>
                            <h2 class="text-white"> <%= @icreports %>
                            </h2>
                          </div>
                          
                        </div>
                       
                      </div>
                    </div>
                      </div>
                      
                      </div><br><br>
                       <div class="row">
                      <div class="col-sm-4">
                        <div class="card mb-3 mb-sm-0" style="background-color: #d926d9 ; color: white;">
                          <div class="card-body py-3 px-4">
                            <p class="m-0 survey-head" style="color: white;">Complaints</p>
                            <div class="d-flex justify-content-between align-items-end flot-bar-wrapper">
                              <div>
                                <h3 class="m-0 survey-value"> <%= @complaints %></h3>
                                
                              </div>
                              
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="card mb-3 mb-sm-0" style="background-color: #A569BD ; color: white;">
                          <div class="card-body py-3 px-4">
                            <p class="m-0 survey-head" style="color: white;">Files</p>
                            <div class="d-flex justify-content-between align-items-end flot-bar-wrapper">
                              <div>
                                <h3 class="m-0 survey-value"> <%= @files %></h3>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="card" style="background-color: #CB4335 ; color: white;">
                          <div class="card-body py-3 px-4">
                            <p class="m-0 survey-head" style="color: white;">RSA</p>
                            <div class="d-flex justify-content-between align-items-end flot-bar-wrapper">
                              <div>
                                <h3 class="m-0 survey-value"> <%= @rsa %></h3>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div><br><br>

                    <h5><b>Why SRS Manager Software ?</b></h5>
                     <p style="color: #7F8C8D;">Support Plan Review 6 month countdown and reminder ,
                      Multiple staff logins with varying permissions ,
                      AO and community visitor login for easy accessed areas ,
                      Forms designed with familiarity of existing paperwork & easy of use ,
                      Easy referencing, archiving & residents easily discharged and returned ,
                      Refrence directly from database & print for filing ensures a smoother transition from previous system ,
                      Offsite backups ensure data is always secured and free from total loss, even more so than paper based ,
                      Improved communication around resident care and changes ,
                      Network ready for multiple computers ,
                      Time saved & continuity of data being entered once then populated throughout other forms ,
                      Easier understanding & confidence in compliance to regulations
                      Appointments, contacts, invoicing, writing letters, writing in staff communication, referencing any information or history all done in one place instead of multiple books, files or programs.</p> 
                    

                    </div>
                    
                  </div>
                </div>

              </div>
            </div>
            </div>
            </div>
          </div>

         
                <!--browser stats ends-->
              </div>
            </div>
          </div>

app/views/home/invoice.html.erb
<div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>INVOICE</b></h3>
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#"></a></li>
                  <li class="breadcrumb-item active" aria-current="page"></li>
                </ol>
              </nav>
            </div>
            <div class="row">


              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">Invoice</h4>
                    <p class="card-description">SRS Manager Supported residential service</p>
                    <form class="forms-sample">
                      <div class="form-group">
                        <label for="exampleInputinvoice">Invoice paid ? Yes/No</label>
                        <input type="radio" class="form-control" id="exampleInputinvoice" placeholder="Invoice paid ? Yes/No" />
                        <label for="exampleInputinvoiceno">Invoice No</label>
                        <input type="radio" class="form-control" id="exampleInputinvoiceno" placeholder="Invoice No" />
                        <label for="exampleInputdate">Invoice Date</label>
                        <input type="radio" class="form-control" id="exampleInputdate" placeholder="Invoice Date" />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputto">To</label>
                        <input type="text" class="form-control" id="exampleInputto" placeholder="To" />   
                      </div>
                      <div class="form-group">
                        <label for="exampleInputatt">ATT</label>
                        <input type="text" class="form-control" id="exampleInputatt" placeholder="ATT" />   
                      </div>
                      <div class="form-group">
                        <label for="exampleInputre">RE</label>
                        <input type="text" class="form-control" id="exampleInputre" placeholder="RE" />   
                      </div>
                      <table style="width:100%">
                        <style>
                        table, th, td {
                        border: 1px solid black;
                         border-collapse: collapse;
                         }
                       </style>
                       <thead>
                        <tr>
                          <th>Description</th>
                          <th>Price</th>
                          <th>GST</th>
                          <th>Q.T.Y</th>
                          <th>TOTAL</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td></td>
                        </tr>
                        <tr></tr>
                        <tr></tr>
                      </tbody>
                      </table><br>
                     <div class="form-group">
                        <label for="exampleInputduration">Duration of Stay</label>
                        <input type="text" class="form-control" id="exampleInputduration" placeholder="Duration of Stay" />   
                      </div>
                      <div class="form-group">
                        <label for="exampleInputfrom">From Date</label>
                        <input type="text" class="form-control" id="exampleInputfrom" placeholder="From Date" />   
                      </div>
                       <div class="form-group">
                        <label for="exampleInputtodate">To Date</label>
                        <input type="text" class="form-control" id="exampleInputtodate" placeholder="To Date" />   
                      </div>
                       <div class="form-group">
                        <label for="exampleInputstaff">Staff Manager</label>
                        <input type="text" class="form-control" id="exampleInputstaff" placeholder="Staff Manager" />   
                      </div>
                      <div class="form-group">
                        <label for="exampleInputposition">Position</label>
                        <input type="text" class="form-control" id="exampleInputposition" placeholder="Position" />   
                      </div>
                      <button type="submit" class="btn btn-primary mr-2"> Submit </button>
                      <button class="btn btn-light">Cancel</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

app/views/home/menu.html.erb
<div class="main-panel">

            <div class="row" style="width: 1000px; padding: 10px; ">
              <div class="col-12 grid-margin stretch-card" >

               <div class="card" style="background-color: #475CB8;">
                 <div class="card-body">
                  </div>
                  <div class="row" style="padding-left: 30px;">
                    <div class="col-3 grid-margin stretch-card" style="padding-left: 20px;">
                    <div class="row">
                      <div class="card" style="background-color: #475CB8;height: 280px;width: 220px;" >
                        <div class="card-header"  style="color: white;background-color: #996600;">
                          Resident
                        </div>
                        <div class="card-body" style="align-items: center;">
                        <p class="card-description"> <u> <%= link_to "Resident Records", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Support Plan", support_plans_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "RSA", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Incident Reports", incident_reports_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Transfer Forms", transfer_details_path ,:style => "color :white;" %>
                        </u></p>
                      </div>
                    </div><br>
                    <div class="row" style="padding-left: 15px;padding-top: 5px;">

                      <div class="card" style="background-color: #475CB8;height: 300px;width: 220px;" >
                        <div class="card-header"  style="color: white;background-color: #996600;">
                          Charts
                        </div>
                        <div class="card-body" style="align-items: center;">
                        <p class="card-description"> <u> <%= link_to "Behaviour Charts", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Bowel Chart", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Turn & Reposition Log", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Wieght-BSL's-BP", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Wound Register", residents_path ,:style => "color :white;" %>
                        </u></p>
                      </div>
                        

                    </div>
                    </div>
                        
                     </div>

                    </div>
                    <div class="col-3 grid-margin stretch-card" >
                      <div class="row" style="padding-left: 15px;">

                      <div class="card" style="background-color: #475CB8;" style="padding: 10px;height: px;">
                        <div class="card-header"  style="color: white;background-color: #996600;">
                          Office
                        </div>
                        <div class="card-body" style="align-items: center;">
                        <p class="card-description"> <u> <%= link_to "Bookings", bookings_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Complaints", complaints_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Files", file_reports_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Contact List", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Fax Cover Sheet", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Invoices", invoice_home_index_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Letters", residents_path ,:style => "color :white;" %>
                        </u></p>
                      </div>
                        
                     </div>     
                         <div class="col-3 grid-margin stretch-card" style="padding-left: 20px;">
                      <div class="row" style="padding-left: 20px;">

                      <div class="card" style="background-color: #475CB8;height: 200px;width: 230px;" >
                        <div class="card-header"  style="color: white;background-color: #996600;">
                          Apppintments
                        </div>
                        <div class="card-body" style="align-items: center;">
                        <p class="card-description"> <u> <%= link_to "Apppintments", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Doctor", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Recurring Apps", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>   
                        
                     </div>
                        
                     </div><br>
                     <div class="row" style="padding-top: 20px;padding-left: 15px;">
                        <div class="card" style="background-color: #475CB8; height: 200px; width: 230px;" >
                        <div class="card-header"  style="color: white;background-color: #996600;">
                          Medication
                        </div>
                        <div class="card-body" style="align-items: center;">
                        <p class="card-description"> <u> <%= link_to "Dialy Chart", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Prescribed", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Non Prescribed", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                        
                        
                     </div>
                   </div><br>
                        
              

                    </div>

                    </div>
            
                  </div><br><br>
                     <div class="card" style="background-color: #475CB8; height: 200px;width: 400px;">
                        <div class="card-header"  style="color: white;background-color: #996600;">
                          Admin
                        </div>
                        <div class="card-body" style="align-items: left;">
                          <div class="row">
                            <div class="col-6">
                              <p class="card-description"> <u> <%= link_to "Staff Records", staff_rosters_path ,:style => "color :white;" %>
                              </u></p>
                              <p class="card-description"> <u> <%= link_to "Staff Review", residents_path ,:style => "color :white;" %>
                              </u></p>
                              <p class="card-description"> <u> <%= link_to "Meeting", residents_agreements_path ,:style => "color :white;" %>
                              </u></p>
                            </div>
                             <div class="col-6">
                              <p class="card-description"> <u> <%= link_to "Log Audit Page", residents_path ,:style => "color :white;" %>
                              </u></p>
                              <p class="card-description"> <u> <%= link_to "Edit Roaster", residents_path ,:style => "color :white;" %>
                              </u></p>
                              <p class="card-description"> <u> <%= link_to "CPR Due Report", residents_agreements_path ,:style => "color :white;" %>
                              </u></p>
                            </div>
            
                            
                          </div>

                        
                      </div>
                    </div>

                    </div>

               

                    <div class="col-3 grid-margin stretch-card" style="padding-left: 30px;">
                      <div class="row" style="padding-right: 20px;padding-left: 50px;">

                      <div class="card" style="background-color: #475CB8;height: 270px;width: 215px; " >
                        <div class="card-header"  style="color: white;background-color: #996600;">
                          Staff
                        </div>
                        <div class="card-body" style="align-items: center;">
                        <p class="card-description"> <u> <%= link_to "Read Handover", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Create Handover", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Create Private Messages", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "View Roaster", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                        
                     </div>
                        
                     </div><br>
                     <div class="row" style="padding-top: 20px;padding-left: 15px;">
                        <div class="card" style="background-color: #475CB8;height: 350px;width: 215px; " >
                        <div class="card-header"  style="color: white;background-color: #996600;">
                          Reports
                        </div>
                        <div class="card-body" style="align-items: center;">
                        <p class="card-description"> <u> <%= link_to "Bed List", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Incident History", residents_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Complaint History ", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                        <p class="card-description"> <u> <%= link_to "Progress Note", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                          <p class="card-description"> <u> <%= link_to "Resident Details", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                         <p class="card-description"> <u> <%= link_to "Resident Summary", residents_agreements_path ,:style => "color :white;" %>
                        </u></p>
                        
                     </div>
                   </div><br>
                        
                     </div>

                    </div>

                    </div>
            
                  </div>
 
                    
            </div><br><br>
            </div>
            </div>
          </div>

          
                <!--browser stats ends-->
             
          </div>

app/views/home/show.html.erb
<div class="main-panel">
	<div class="content-wrapper">
	  <div class="page-header">
	    <h3 class="page-title"><b>My Profile</b></h3>
	   
	  </div>
	  <div class="row">
	  	<div class="col-12 grid-margin stretch-card">

		<div class="card">
                  <div class="card-body">
                    <p class="card-description">Update Profile</p>
            <%= form_with( remote: true , class: "forms-sample", url: users_home_index_path(current_user), method: :put) do |f| %>
                      <div class="form-group">
                        <label for="exampleInputname">Name</label>
                     <%= f.text_field :name, autofocus: true, autocomplete: "user", :class => "form-control", value:@user.name %>                      
                      </div>
                       <div class="form-group">
                        <label for="exampleaddress">Email Address</label>
                        <%= f.text_field :email, autofocus: true, autocomplete: "Email", :class => "form-control", value:@user.email %>
                      </div>
                      <div class="form-group">
                        <label for="exampleInputtelephone">Password</label>
                        <input type="text" class="form-control" id="exampleInputtelephone" value="<%= @user.password %>" />
                      </div>
											<button type="submit" class="btn btn-primary mr-2"> Update </button>
                      <button class="btn btn-light">Cancel</button>                      
<% end %>                     </div>
                </div>
              </div>
            </div>
          </div>
          </div>
          

app/views/home/users.html.erb
<div class="main-panel">
          <div class="content-wrapper pb-0">
            <div class="page-header">
              <h3 class="page-title"><b>Users</b></h3>
               <div class="col-md-8">
            
              </div>
             
            </div>
           <div class="row">
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                   
                    <div class="table-responsive">
                      <table class="table">
                        <thead>
                          <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Pwd</th>
                           
                            <th>Created_at</th>
                            <th style="width: 500px;align-content: center;">Action</th>
                          </tr>
                        </thead>
                        
    <tbody>
      <% @users.each_with_index do |user, i| %>
        <tr id='users_ROW_<%= user.id %>'>
          <td>
            <span><%= i+1 %></span>
          </td>
          <td>
            <span><%= user.name %></span>
          </td>
          <td>
            <span><%= user.try(:email) %></span>
          </td>
         <td>
            <span><%= user.try(:password) %></span>
          </td>
          <td>
            <span><%= user.created_at.in_time_zone("Asia/Muscat").strftime('%d %B %Y, %H:%M') if user.created_at %></span>
          </td>
          
        </tr>
      <% end %>
    </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>