config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
	  root 'devise/sessions#new'
	end
  resources :home do
    collection do
      get :menu
      get :users
      put 'update/:id/', to: 'home#update'
      get :invoice
    end
   
  end 
  resources :residents 
  resources :residents_agreements 
  resources :support_plans 
  resources :complaints 
  resources :bookings 
  resources :incident_reports 
  resources :srs_referals 
  resources :profile 
  resources :transfer_details 
  resources :file_reports
  resources :staff_rosters

end

app/models/support_plan.rb
class SupportPlan < ApplicationRecord
 
    
end

app/controllers/support_plans_controller.rb
# derived from base controller
class SupportPlansController < BaseController

  #authenticate if user logged.
  before_action :authenticate_user!

	def index
   	@page_title = "Support Plans | Home"
   	get_collection
	end
	
  def new
    new_support_plan
   	@page_title = "Support Plans | New Support Plans"   
	end
	
	def show
    @page_title = "Support Plan"
		@support_plan=SupportPlan.find(params[:id])
	end
	
	def edit
		@support_plan=SupportPlan.find(params[:id])
   	@page_title = "Support Plans | Update Support Plans"   	
	end
  
  def create
	 	@support_plan=SupportPlan.new(permitted_params)
    if @support_plan.valid?
      @support_plan.save
      redirect_to support_plans_path
	 	else
      redirect_to home_index_path

	 	end
	end

	def update
    @support_plan=SupportPlan.find(params[:id])
	  @support_plan.update(permitted_params)
	  if @support_plan.save
      redirect_to support_plans_path
		else
      redirect_to home_index_path

		end
	end
	
  def destroy
		@support_plan = SupportPlan.find(params[:id])
    if @support_plan.destroy
      redirect_to support_plans_path
    else
      redirect_to home_index_path
    end
  end
    
  # --------------
  # Fetch Methods
  # --------------

	private

	def permitted_params
    params.require(:support_plan).permit(:user_name, :Hygiene, :nutrition, :health_care, :medication, :social_contact, :behaviour, :goals, :mobility)
	end

  def new_support_plan
    @support_plan = SupportPlan.new
  end

  def existing_support_plan
    @support_plan = SupportPlan.find_by_id(params[:id])
  end

  def get_collection
    @relation = SupportPlan.where("")

    apply_filters

    @order_by = "created_at DESC" unless @order_by
    @support_plans = @r_objects = @relation.order(@order_by).all #page(@current_page).per(@per_page)
  end
  
  def apply_filters
    @query = params[:q]
    @relation = @relation.search(@query) if @query && !@query.blank?
    #@relation = @relation.search_only_name(params[:filters].try(:[], :name))
    
  end





	
end

app/views/support_plans/edit.html.erb
<div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>Update Support Plan</b></h3>
             
            </div>
            <div class="row">
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                       <%= render partial: 'support_plans/form/form' %>

                  	</div>
                </div>
              </div>
            </div>
          </div>
        </div>

app/views/support_plans/index.html.erb
<div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>Support Plans</b></h3>
               <div class="col-md-4">
            <%= link_to '+ Add New Support Plan', new_support_plan_path, :class =>"btn btn-success", :remote => true %>
  
              </div>
             
            </div>
           <div class="row">
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                   
                    <div class="table-responsive">
                      <table class="table" style="border-color: black;border: 1px;">
                        <thead style="background-color: #1294a3;color: white;">
                          <tr>
                            <th>#</th>
                            <th>support_plans By</th>
                            <th>Created_at</th>
                            <th style="align-content: center;">Action</th>
                            <th></th>
                            <th></th>
                          </tr>
                        </thead>
                        
    <tbody>
      <% @support_plans.each_with_index do |support_plan, i| %>
        <tr id='support_plans_ROW_<%= support_plan.id %>'>
          <td>
            <span><%= i+1 %></span>
          </td>
          <td>
            <span><%= support_plan.user_name %></span>
          </td>
          
          <td>
            <span><%= support_plan.created_at.in_time_zone("Asia/Muscat").strftime('%d %B %Y, %H:%M') if support_plan.created_at %></span>
          </td>
          <td>
            <%= button_to support_plan_path(support_plan),:method => :get, :class => "btn-success" do %><i class="fa fa-eye"></i><% end %></td>
            <td><%= button_to edit_support_plan_path(support_plan), :method => :get, :remote => true, :class => "btn-success" do %><i class="fa fa-edit"></i><% end %></td>
            <td><%= button_to support_plan_path(support_plan), :method => :delete, :remote => true, data: {confirm: "Are you sure you want to delete this?"}, :class => "btn-success" do %><i class="fa fa-trash"></i><% end %>
           
          </td>
        </tr>
      <% end %>
    </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
      </div>

app/views/support_plans/new.html.erb
<div class="main-panel">
          <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>Add New Support Plan</b></h3>
             
            </div>
            <div class="row">
              <div class="col-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
  					         <%= render partial: 'support_plans/form/form' %>

                  	</div>
                </div>
              </div>
            </div>
          </div>
        </div>

app/views/support_plans/show.html.erb
<div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
              <h3 class="page-title"><b>Support Plans</b></h3>
               <div class="col-md-4">
            <%= link_to '+ Add New Support Plan', new_support_plan_path, :class =>"btn btn-success", :remote => true %>
  
              </div>
             
            </div>
           <div class="row">
              <div class="col-12 grid-margin stretch-card">
              	<div class="card">
                  <div class="card-body">
     				 <form class="forms-sample">
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleInputPersonal">Name</label>
                      </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @support_plan.user_name %></label>

                      </div>
                     </div>
						<div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleInputPersonal">Personal Hygiene</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @support_plan.Hygiene %></label>
                         
                      </div>
                  </div>
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleInputEating">Eating and Nutrition </label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @support_plan.nutrition %></label>
                      </div>
                      </div>	
                      <div class="row">
                      <div class="col-3">
                       <div class="form-group">
                        <label for="exampleInputMobility">Mobility</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @support_plan.mobility %></label>
  					</div>
  					</div>
  					<div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleInputHealth">Health Care</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @support_plan.health_care %></label>
                      </div>
                      </div>
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleSelectMedication">Medication</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @support_plan.medication %></label>
                      </div>
                      </div>
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleSelectSocial">Social Contact &<br> Emotional wellbeing</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @support_plan.social_contact %></label>
                        </div>
                      </div>
                      <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleSelectBehaviour">Behaviour</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @support_plan.behaviour %></label>
   					 </div>
   					 </div>
   					 <div class="row">
                      <div class="col-3">
                      <div class="form-group">
                        <label for="exampleSelectGoal">Goals/Finances/Other</label>
                        </div>
                     </div>
                      <div class="col-9">
                        <label for="exampleInputPersonal">:&nbsp;&nbsp;<%= @support_plan.goals %></label>
          				 </div>
                          </div>
                      
                      
                     </form>
                  </div>
              </div>

              </div>
          </div>
      </div>
  </div>